<?php

return [
    'posts' => [
        [
            'slug' => 'end-of-tenancy-cleaning-checklist-cape-town',
            'title' => 'End-of-Tenancy Cleaning Checklist: How to Get Your Full Deposit Back in Cape Town',
            'excerpt' => 'Landlords and agents in the Northern Suburbs inspect harder than ever. Here is the room-by-room checklist our crews use to help tenants recover their full deposit.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/services/end_of_tenancy.avif',
            'date' => '2026-06-24',
            'read_time' => 8,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'deep-clean-cost-cape-town-pricing-guide',
            'title' => 'How Much Does a Deep Clean Cost in Cape Town? 2026 Pricing Guide',
            'excerpt' => 'Deep cleaning quotes vary wildly across Cape Town. We break down what actually drives the price, from property size to the state of your kitchen and bathrooms.',
            'category' => 'Pricing',
            'cover' => '/images/works/services/deep_cleaning.avif',
            'date' => '2026-06-10',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'post-construction-cleaning-what-to-expect',
            'title' => 'Post-Construction Cleaning: What to Expect Before You Move In',
            'excerpt' => 'Builder dust gets into everything. Here is how a professional post-construction clean works, phase by phase, before you unpack a single box.',
            'category' => 'Post-Construction',
            'cover' => '/images/works/services/post_construction.avif',
            'date' => '2026-05-28',
            'read_time' => 7,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'signs-your-home-needs-a-deep-clean',
            'title' => '7 Signs Your Home Needs a Professional Deep Clean',
            'excerpt' => 'A quick weekly tidy is not the same as a deep clean. These seven warning signs tell you when it is time to book one in.',
            'category' => 'Deep Cleaning',
            'cover' => '/images/works/hero_clean.avif',
            'date' => '2026-05-14',
            'read_time' => 5,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'move-in-vs-move-out-cleaning-difference',
            'title' => 'Move-In vs Move-Out Cleaning: What is the Difference?',
            'excerpt' => 'They sound similar but the priorities are completely different. Here is how to choose the right service depending on which side of the move you are on.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/home.avif',
            'date' => '2026-04-30',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'eco-friendly-cleaning-is-it-really-better',
            'title' => 'Eco-Friendly Cleaning: Is It Really Better for Your Home?',
            'excerpt' => 'Green cleaning products are everywhere, but do they actually clean as well as traditional chemicals? We tested the trade-offs so you do not have to.',
            'category' => 'Tips',
            'cover' => '/images/works/we_clean.avif',
            'date' => '2026-04-16',
            'read_time' => 5,
            'author' => 'SpringKleaners Team',
        ],
    ],
];
