<?php

return [
    'posts' => [
        [
            'slug' => 'end-of-tenancy-cleaning-checklist-cape-town',
            'title' => 'End-of-Tenancy Cleaning Checklist: How to Get Your Full Deposit Back in Cape Town',
            'excerpt' => 'Landlords and agents in the Northern Suburbs inspect harder than ever. Here is the room-by-room checklist our crews use to help tenants recover their full deposit.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/services/end_of_tenancy.avif',
            'date' => '2026-06-24',
            'read_time' => 8,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'deep-clean-cost-cape-town-pricing-guide',
            'title' => 'How Much Does a Deep Clean Cost in Cape Town? 2026 Pricing Guide',
            'excerpt' => 'Deep cleaning quotes vary wildly across Cape Town. We break down what actually drives the price, from property size to the state of your kitchen and bathrooms.',
            'category' => 'Pricing',
            'cover' => '/images/works/services/deep_cleaning.avif',
            'date' => '2026-06-10',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'post-construction-cleaning-what-to-expect',
            'title' => 'Post-Construction Cleaning: What to Expect Before You Move In',
            'excerpt' => 'Builder dust gets into everything. Here is how a professional post-construction clean works, phase by phase, before you unpack a single box.',
            'category' => 'Post-Construction',
            'cover' => '/images/works/services/post_construction.avif',
            'date' => '2026-05-28',
            'read_time' => 7,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'signs-your-home-needs-a-deep-clean',
            'title' => '7 Signs Your Home Needs a Professional Deep Clean',
            'excerpt' => 'A quick weekly tidy is not the same as a deep clean. These seven warning signs tell you when it is time to book one in.',
            'category' => 'Deep Cleaning',
            'cover' => '/images/works/hero_clean.avif',
            'date' => '2026-05-14',
            'read_time' => 5,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'move-in-vs-move-out-cleaning-difference',
            'title' => 'Move-In vs Move-Out Cleaning: What is the Difference?',
            'excerpt' => 'They sound similar but the priorities are completely different. Here is how to choose the right service depending on which side of the move you are on.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/home.avif',
            'date' => '2026-04-30',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'eco-friendly-cleaning-is-it-really-better',
            'title' => 'Eco-Friendly Cleaning: Is It Really Better for Your Home?',
            'excerpt' => 'Green cleaning products are everywhere, but do they actually clean as well as traditional chemicals? We tested the trade-offs so you do not have to.',
            'category' => 'Tips',
            'cover' => '/images/works/we_clean.avif',
            'date' => '2026-04-16',
            'read_time' => 5,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'end-of-tenancy-cleaning-cost-cape-town',
            'title' => 'How Much Does End-of-Tenancy Cleaning Cost in Cape Town?',
            'excerpt' => 'From R1,200 for a 2-bed, 1-bath property, scaling with bedrooms, bathrooms, and condition. Here is exactly how the price is built up.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/services/end_of_tenancy.avif',
            'date' => '2026-07-09',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'office-cleaning-cost-cape-town',
            'title' => 'How Much Does Office Cleaning Cost in Cape Town?',
            'excerpt' => 'Office cleaning is usually priced per square metre, not per hour. Here is how the R10/m² model works, and when a monthly contract makes more sense.',
            'category' => 'Office Cleaning',
            'cover' => '/images/works/we_clean.avif',
            'date' => '2026-07-07',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'post-construction-cleaning-checklist',
            'title' => 'The Ultimate Post-Construction Cleaning Checklist',
            'excerpt' => 'Every surface builders touch, room by room, before a new build or renovation is genuinely move-in ready.',
            'category' => 'Post-Construction',
            'cover' => '/images/works/services/post_construction.avif',
            'date' => '2026-07-05',
            'read_time' => 7,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'deep-cleaning-vs-regular-cleaning',
            'title' => 'Deep Cleaning vs. Regular Cleaning: What\'s Actually Different?',
            'excerpt' => 'They sound like the same service at two price points. They are not. Here is exactly where the line sits, and how to choose.',
            'category' => 'Deep Cleaning',
            'cover' => '/images/works/services/deep_cleaning.avif',
            'date' => '2026-07-03',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'who-pays-for-end-of-lease-cleaning-south-africa',
            'title' => 'Who Pays for End-of-Lease Cleaning in South Africa? A Legal Overview',
            'excerpt' => 'A general guide to how South African lease agreements typically treat cleaning obligations and deposit deductions — not legal advice, but a useful starting point.',
            'category' => 'End-of-Tenancy',
            'cover' => '/images/works/home.avif',
            'date' => '2026-07-01',
            'read_time' => 7,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'office-cleanliness-productivity',
            'title' => 'Why Office Cleanliness Affects Productivity (and Client Perception)',
            'excerpt' => 'A clean office is not just about appearances. Here is how workplace hygiene actually shapes staff wellbeing and the impression clients walk away with.',
            'category' => 'Office Cleaning',
            'cover' => '/images/works/2.png',
            'date' => '2026-06-29',
            'read_time' => 5,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'spring-cleaning-cape-town-guide',
            'title' => 'Spring Cleaning in Cape Town: The Complete Seasonal Guide',
            'excerpt' => 'Sea-air salt residue, wind-blown dust, and winter grime — a room-by-room guide to a genuine seasonal reset for Cape Town homes.',
            'category' => 'Tips',
            'cover' => '/images/works/home.avif',
            'date' => '2026-06-27',
            'read_time' => 7,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'meet-the-team-behind-springkleaners',
            'title' => 'Meet the Team Behind SpringKleaners',
            'excerpt' => 'A registered company, background-checked staff, and the real people our clients ask for by name.',
            'category' => 'About',
            'cover' => '/images/works/1.png',
            'date' => '2026-06-25',
            'read_time' => 4,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'why-we-publish-our-prices',
            'title' => 'Why We Publish Our Prices When Other Cleaning Companies Don\'t',
            'excerpt' => 'Real starting prices, published on every service page, instead of a "request a quote" black box. Here is why that matters.',
            'category' => 'Trust',
            'cover' => '/images/works/3.png',
            'date' => '2026-06-23',
            'read_time' => 4,
            'author' => 'SpringKleaners Team',
        ],
        [
            'slug' => 'airbnb-short-let-cleaning-cape-town-hosts',
            'title' => 'Airbnb & Short-Let Cleaning: What Cape Town Hosts Need to Know Between Guests',
            'excerpt' => 'A faster, tighter-scope reset between guests — what a proper turnover clean actually covers, and how to keep your listing photo-ready.',
            'category' => 'Tips',
            'cover' => '/images/works/we_clean.avif',
            'date' => '2026-06-21',
            'read_time' => 6,
            'author' => 'SpringKleaners Team',
        ],
    ],
];
