<?php

return [

    'deep-cleaning' => [
        'meta_title' => 'Deep Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Professional deep cleaning in Milnerton, Blouberg, Table View, Parklands & Cape Town\'s Northern Suburbs. Free inspection, fully insured, from R1,200. Book online.',
        'label' => 'Deep Cleaning',
        'h1_line1' => 'Deep Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'A thorough, top-to-bottom clean for homes and businesses that deserve better than a quick tidy-up. Our teams work room by room — kitchens, bathrooms, appliances, skirting and cupboard interiors — so nothing gets missed. Ideal for a seasonal refresh, pre-event clean, or simply reclaiming a spotless home without lifting a finger.',
        'included' => [
            'Kitchen & bathroom deep clean',
            'All rooms vacuumed & mopped',
            'Inside appliances cleaned',
            'Baseboards & skirting wiped',
            'Cupboard interiors wiped down',
            'Light fixtures & switches dusted',
        ],
        'ideal_for' => 'Busy homeowners, growing families, and anyone who wants a spotless reset without doing the work themselves.',
        'blog_categories' => ['Deep Cleaning', 'Tips', 'Pricing'],
        'hero_image' => '/images/works/services/deep_cleaning.avif',
        'faqs' => [
            ['q' => 'How long does a deep clean take?', 'a' => 'On average, a deep clean takes around 4 hours, depending on the size of the property and the number of bedrooms and bathrooms. We give you an accurate time estimate after the free inspection.'],
            ['q' => 'How is deep cleaning different from a regular clean?', 'a' => 'A regular clean maintains a space that\'s already tidy. A deep clean resets it — we get into the details a weekly clean skips, like inside appliances, cupboard interiors, skirting boards and built-up grime in bathrooms and kitchens.'],
            ['q' => 'Do I need to be home during the clean?', 'a' => 'No. Many of our clients give access instructions and return to a spotless home. If you\'d prefer to be present, that\'s completely fine too.'],
            ['q' => 'What\'s the price based on?', 'a' => 'Pricing starts from R1,200 and scales with the number of bedrooms, bathrooms and any add-ons you choose (like interior windows or a balcony clean). You\'ll see the full breakdown before you confirm.'],
        ],
    ],

    'end-of-tenancy' => [
        'meta_title' => 'End-of-Tenancy Cleaning Cape Town | Move-In/Move-Out | SpringKleaners',
        'meta_description' => 'End-of-tenancy cleaning to landlord & letting-agent standard across Cape Town\'s Northern Suburbs. Help protect your deposit. Free inspection, from R1,200. Book online.',
        'label' => 'End-of-Tenancy Cleaning',
        'h1_line1' => 'End-of-Tenancy Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Move-in and move-out cleaning to the standard landlords and letting agents actually check for. We cover everything in a deep clean, plus walls, windows, tracks and a full condition checklist — built to help tenants protect their deposit and help landlords hand over a move-in ready property.',
        'included' => [
            'Everything in a Deep Clean, plus:',
            'Walls wiped & marks removed',
            'Windows & tracks cleaned',
            'Inside all cupboards & wardrobes',
            'Condition checklist included',
            'Kitchen appliances deep cleaned',
        ],
        'ideal_for' => 'Tenants moving out, landlords preparing a handover, and letting agents who need a property inspection-ready.',
        'blog_categories' => ['End-of-Tenancy'],
        'hero_image' => '/images/works/services/end_of_tenancy.avif',
        'faqs' => [
            ['q' => 'Will this help me get my deposit back?', 'a' => 'It\'s the single biggest factor in most deposit disputes. We clean to the standard landlords and letting agents inspect against, and we provide a condition checklist you can use as proof of the clean\'s scope.'],
            ['q' => 'What\'s included that a normal clean doesn\'t cover?', 'a' => 'End-of-tenancy adds wall mark removal, full window and track cleaning, and cupboard interiors — the details agents specifically check during a move-out inspection.'],
            ['q' => 'Can you work around a tight moving timeline?', 'a' => 'Yes, in most cases we can accommodate same-week bookings. Message us on WhatsApp with your move-out date and we\'ll confirm availability immediately.'],
            ['q' => 'Do landlords book this too, or only tenants?', 'a' => 'Both. We regularly clean for landlords and letting agents preparing a property for new tenants, as well as tenants who want to protect their deposit before handover.'],
        ],
    ],

    'post-construction' => [
        'meta_title' => 'Post-Construction Cleaning Cape Town | Builders Clean | SpringKleaners',
        'meta_description' => 'Post-construction & builders cleaning for new builds and renovations across Cape Town\'s Northern Suburbs. Dust, debris & paint cleanup to move-in ready. From R1,800.',
        'label' => 'Post Construction Cleaning',
        'h1_line1' => 'Post-Construction Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Builder dust gets into everything — window tracks, light fittings, cupboard interiors, air vents. We remove what the builders left behind, from fine dust and paint splatter to adhesive residue, and hand the property back to a genuine move-in ready standard.',
        'included' => [
            'Dust & debris removed',
            'Paint & adhesive cleanup',
            'Windows & frames polished',
            'Floor scrubbing & finishing',
            'Light fittings & vents cleaned',
            'Cupboards wiped inside & out',
        ],
        'ideal_for' => 'Builders, contractors and developers handing over new builds, plus homeowners cleaning up after a renovation.',
        'blog_categories' => ['Post-Construction'],
        'hero_image' => '/images/works/services/post_construction.png',
        'faqs' => [
            ['q' => 'How soon after building work can you clean?', 'a' => 'As soon as the site is safe to enter and major construction work has finished. We recommend booking once trades have wrapped up so the clean doesn\'t need to be repeated after final touch-ups.'],
            ['q' => 'Can you handle heavy dust and paint residue?', 'a' => 'Yes, that\'s the core of this service. We use equipment and techniques specifically suited to construction-grade dust, paint splatter and adhesive residue that a standard clean isn\'t equipped for.'],
            ['q' => 'How long does a post-construction clean take?', 'a' => 'On average around 6 hours, though this varies significantly with the size of the build and how much residue is left behind. We confirm an accurate estimate after the free inspection.'],
            ['q' => 'Do you work with contractors and developers directly?', 'a' => 'Yes, we regularly work directly with builders, contractors and developers to schedule handover cleans around project timelines.'],
        ],
    ],

    'office-commercial-cleaning' => [
        'meta_title' => 'Office & Commercial Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Office and commercial cleaning across Cape Town\'s Northern Suburbs, priced per m². Century City, Montague Gardens & Parklands office parks. From R10/m², R850 minimum call-out.',
        'label' => 'Office & Commercial Cleaning',
        'h1_line1' => 'Office & Commercial Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Reception areas, open-plan floors, boardrooms and staff kitchens that stay presentable for clients and comfortable for your team. We work around your business hours — most contracts are cleaned over weekends or before opening — and coordinate directly with building management for after-hours access in body-corporate blocks and multi-tenant office parks across Century City, Montague Gardens and Parklands.',
        'included' => [
            'Workstations & desks wiped down',
            'Reception, boardroom & meeting rooms',
            'Kitchen & staff canteen area cleaned',
            'Ablutions fully sanitised & restocked',
            'Bins emptied, liners replaced',
            'Carpet tiles vacuumed, hard floors mopped',
            'Glass partitions & entrance doors',
            'High-touch points (handles, switches, buttons)',
        ],
        'ideal_for' => 'Small-to-medium offices, professional practices, and commercial units in Cape Town\'s Northern Suburbs office parks who want a fixed per-m² rate instead of an opaque contract quote.',
        'blog_categories' => ['Office Cleaning', 'Pricing'],
        'hero_image' => '/images/works/we_clean.avif',
        'pricing_mode' => 'quote',
        'pricing_headline' => 'R10',
        'pricing_unit' => 'per m² / visit',
        'pricing_notes' => [
            'R10 per m² per visit',
            'R850 minimum call-out',
            'Custom quote for multi-floor or multi-tenant contracts',
        ],
        'cta_label' => 'Request a Quote',
        'faqs' => [
            ['q' => 'How is office cleaning priced?', 'a' => 'R10 per m² per visit, with an R850 minimum call-out for smaller units. We measure your actual floor area during a free walkthrough so the quote is exact, not estimated. Multi-floor or multi-tenant buildings get a custom monthly contract quote instead, since per-m² pricing stops scaling cleanly at that size.'],
            ['q' => 'Can you clean outside business hours?', 'a' => 'Yes — most of our office contracts are cleaned over the weekend or before opening on Monday, so your team never works around us. We coordinate access with building management or body corporates ahead of time for secure office parks.'],
            ['q' => 'Do we need a long-term contract?', 'a' => 'No. We quote per visit or per month, whichever suits your business — there\'s no minimum-term lock-in for standard office cleaning. Multi-floor or multi-tenant contracts are quoted individually based on scope.'],
            ['q' => 'What size offices do you service?', 'a' => 'From single-office professional practices through to multi-room commercial units in Century City, Montague Gardens and the wider Northern Suburbs. Larger multi-floor or multi-tenant buildings are welcome too — those just move to a custom quote rather than the standard per-m² rate.'],
        ],
    ],

    'recurring-house-cleaning' => [
        'meta_title' => 'Recurring House Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Weekly & bi-weekly recurring house cleaning across Cape Town\'s Northern Suburbs. A lighter maintenance clean between Deep Cleans, from R750/visit. Book online.',
        'label' => 'Recurring House Cleaning',
        'h1_line1' => 'Recurring House Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'A lighter, maintenance-level clean for homes that are already in good shape and just need upkeep between resets — surfaces dusted, floors done, kitchen and bathroom kept guest-ready. It\'s the standing weekly or bi-weekly visit that keeps a home at the standard your last Deep Clean left it, without redoing the inside-appliance and cupboard-interior work every time.',
        'included' => [
            'All rooms tidied, dusted & vacuumed',
            'Kitchen surfaces & sink cleaned',
            'Bathrooms cleaned & restocked check',
            'Floors vacuumed & mopped',
            'Beds made, laundry area tidied',
            'Bins emptied',
        ],
        'ideal_for' => 'Busy households and professionals who\'ve already had a Deep Clean and want to maintain that standard week to week, on a standing weekly or bi-weekly slot.',
        'blog_categories' => ['Deep Cleaning', 'Tips'],
        'hero_image' => '/images/works/home.avif',
        'faqs' => [
            ['q' => 'How is this different from a Deep Clean?', 'a' => 'A Deep Clean resets a home from scratch — inside appliances, cupboard interiors, built-up grime. Recurring cleaning maintains that standard in between, covering the surfaces and rooms that get used day to day, at a lighter (and lower) rate. Most clients pair a periodic Deep Clean with a weekly or bi-weekly recurring visit.'],
            ['q' => 'How often can I book a recurring clean?', 'a' => 'Weekly or bi-weekly, on a standing slot. Because we currently operate weekend cleans with limited daily capacity, we lock in your recurring slot in advance so it\'s reserved before it fills up.'],
            ['q' => 'Do I need to be home during the clean?', 'a' => 'No. Most recurring clients give access instructions once and we let ourselves in and out on the agreed schedule. If you\'d prefer to be present, that\'s fine too.'],
            ['q' => 'What\'s the price based on?', 'a' => 'From R750 per visit for 2 bedrooms and 1 bathroom, plus R100 for each additional bedroom or bathroom — the same scaling model as our Deep Clean, just at a lighter-scope, lower rate.'],
        ],
    ],

    'carpet-cleaning' => [
        'meta_title' => 'Carpet Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Hot-water extraction carpet cleaning across Cape Town\'s Northern Suburbs. Stain, odour & pet-hair treatment, priced per room from R250. R950 minimum call-out.',
        'label' => 'Carpet Cleaning',
        'h1_line1' => 'Carpet Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Hot-water extraction that lifts embedded dirt, pet hair and odours out of the pile, not just off the surface — the difference between a carpet that looks clean and one that actually is. Coastal Northern Suburbs homes deal with more sea-air humidity and sand tracked in underfoot than most, which speeds up musty odour build-up in wall-to-wall carpet; we treat for that as standard, not as an upsell.',
        'included' => [
            'Full pre-inspection & pre-vacuum',
            'Stain & spot pre-treatment',
            'Hot-water extraction deep clean',
            'Pet hair & odour treatment',
            'Deodorising finish',
            'Fast-dry technique (grooming + airflow)',
        ],
        'ideal_for' => 'Homes with wall-to-wall carpeting, pet owners, and end-of-tenancy or pre-sale properties that need carpets brought back to an inspection-ready standard.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/2.png',
        'pricing_mode' => 'quote',
        'pricing_headline' => 'R250',
        'pricing_unit' => 'per room',
        'pricing_notes' => [
            'R250 per room',
            'R950 minimum call-out',
            'Stain, odour & pet-hair treatment included',
        ],
        'cta_label' => 'Request a Quote',
        'faqs' => [
            ['q' => 'How is carpet cleaning priced?', 'a' => 'R250 per room, with an R950 minimum call-out for smaller jobs. We confirm the exact room count and any heavy-stain areas during a free walkthrough before quoting.'],
            ['q' => 'How long does carpet take to dry afterwards?', 'a' => 'Typically a few hours with normal ventilation, thanks to our fast-dry extraction technique — most clients can walk on carpets (in socks) within 2-4 hours, and have full furniture back in place by the next day.'],
            ['q' => 'Can you remove pet stains and odours?', 'a' => 'Yes — pet hair, dander and odour treatment is included as standard, not an add-on. Heavily soiled areas may need an extra pass, which we\'ll flag during the walkthrough.'],
            ['q' => 'Do you clean carpets as part of an end-of-tenancy clean?', 'a' => 'Carpet cleaning is quoted separately from our End-of-Tenancy service, but we regularly book them together for tenants and landlords who need carpets brought back to inspection standard before handover.'],
        ],
    ],

    'upholstery-cleaning' => [
        'meta_title' => 'Upholstery Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Fabric & leather upholstery cleaning across Cape Town\'s Northern Suburbs. Sofas, lounge suites & dining chairs, priced per seat from R150. R800 minimum call-out.',
        'label' => 'Upholstery Cleaning',
        'h1_line1' => 'Upholstery Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Sofas, lounge suites and dining chairs take more daily wear than almost anything else in a home — and fabric and leather need genuinely different treatment to come clean without damage. We assess the material first, then use hot-water extraction for fabric or a specialised leather clean-and-condition process, so the finish protects the upholstery instead of just soaking it.',
        'included' => [
            'Fabric or leather assessment',
            'Full vacuum & pre-treatment',
            'Hot-water extraction (fabric) or leather clean & condition',
            'Stain-specific spot treatment',
            'Deodorising finish',
            'Fast-dry technique',
        ],
        'ideal_for' => 'Family homes with everyday sofa wear, pet owners, and landlords refreshing furnished rental units between tenants.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/3.png',
        'pricing_mode' => 'quote',
        'pricing_headline' => 'R150',
        'pricing_unit' => 'per seat (fabric)',
        'pricing_notes' => [
            'R150 per seat, fabric upholstery',
            '+25% for leather upholstery',
            'R800 minimum call-out',
        ],
        'cta_label' => 'Request a Quote',
        'faqs' => [
            ['q' => 'How is upholstery cleaning priced?', 'a' => 'R150 per seat for fabric upholstery, plus 25% for leather (which needs a different clean-and-condition process). There\'s an R800 minimum call-out for smaller jobs like a single armchair.'],
            ['q' => 'Is the process different for leather vs fabric?', 'a' => 'Yes. Fabric gets hot-water extraction similar to carpet cleaning. Leather is cleaned and conditioned with products suited to the hide, since extraction methods can dry out and crack leather over time.'],
            ['q' => 'Will cleaning remove pet hair and odours?', 'a' => 'Yes, pet hair and odour treatment is included as standard on both fabric and leather upholstery.'],
            ['q' => 'How long before I can use the furniture again?', 'a' => 'Fabric upholstery is usually dry enough for light use within a few hours; we\'ll confirm timing based on the piece and ventilation on the day.'],
        ],
    ],

    'window-cleaning' => [
        'meta_title' => 'Window Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Interior & exterior window cleaning across Cape Town\'s Northern Suburbs. Streak-free glass, frames & tracks, from R1,400 per property or R40 per pane.',
        'label' => 'Window Cleaning',
        'h1_line1' => 'Window Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Streak-free interior and exterior glass, including the frames, sills and tracks that collect sand and salt residue in coastal suburbs like Bloubergstrand, Big Bay and Table View. We clear tracks of grit before washing so windows actually slide smoothly afterwards, not just look clean.',
        'included' => [
            'Interior & exterior glass',
            'Frames & sills wiped down',
            'Tracks cleared of sand & grit',
            'Streak-free squeegee finish',
            'Accessible upper-floor windows (extension pole)',
            'Screens cleaned where removable',
        ],
        'ideal_for' => 'Coastal homes dealing with salt residue, pre-sale and pre-event properties, and anyone whose windows haven\'t had a proper clean in longer than they\'d like to admit.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/premium_photo-1683141112334-d7d404f6e716.avif',
        'pricing_mode' => 'quote',
        'pricing_headline' => 'R1,400',
        'pricing_unit' => 'per property (typical home)',
        'pricing_notes' => [
            'From R1,400 for a typical full property clean',
            'Smaller jobs: R40/pane ground floor, R75/pane upper floor',
            'Custom quote for large or multi-storey properties',
        ],
        'cta_label' => 'Request a Quote',
        'faqs' => [
            ['q' => 'How is window cleaning priced?', 'a' => 'A typical home runs from R1,400 for a full interior-and-exterior clean. For smaller jobs, we quote R40 per pane on the ground floor and R75 per pane upstairs. Large or multi-storey properties get a custom quote after a walkthrough.'],
            ['q' => 'Do you clean upper-floor windows safely?', 'a' => 'Yes, accessible upper floors are cleaned with an extension pole system from the ground or an internal-access point. For properties needing rope access or scaffolding, we\'ll quote that separately with the right safety equipment.'],
            ['q' => 'Can you get rid of salt residue and hard water marks?', 'a' => 'Yes — salt residue from sea air is one of the most common issues we treat in Bloubergstrand, Big Bay and Table View, along with hard water marks and built-up grime in window tracks.'],
            ['q' => 'Do you clean window frames and tracks too, or just the glass?', 'a' => 'Both. Tracks are cleared of sand and grit before we wash the glass, and frames and sills are wiped down as standard — a clean pane in a gritty track doesn\'t actually solve the problem.'],
        ],
    ],

    'airbnb-turnover-cleaning' => [
        'meta_title' => 'Airbnb & Short-Let Turnover Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Fast, photo-ready turnover cleaning for Airbnb & short-let hosts in Cape Town\'s Northern Suburbs. From R900/turnover, weekend changeovers. Book online.',
        'label' => 'Airbnb & Short-Let Turnover Cleaning',
        'h1_line1' => 'Airbnb & Short-Let',
        'h1_line2' => 'Turnover Cleaning',
        'intro' => 'A faster, tighter-scope clean built for the gap between one guest leaving and the next arriving — beds stripped and remade, bathrooms reset, kitchen cleared, and the space left photo-ready for your listing. We currently schedule turnovers within our weekend availability, which suits the Friday-in/Sunday-out pattern common to weekend-getaway short-lets in Big Bay, Blouberg and Bloubergstrand.',
        'included' => [
            'Beds stripped, linen changed & remade',
            'Bathrooms fully reset & restocked',
            'Kitchen cleared, wiped & reset',
            'Floors vacuumed & mopped',
            'Damage/missing-item check reported to host',
            'Photo-ready staging before you re-list',
        ],
        'ideal_for' => 'Airbnb and short-let hosts in the Northern Suburbs with weekend guest changeovers, who need a consistent, photo-ready reset without managing the clean themselves.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/we_clean.avif',
        'faqs' => [
            ['q' => 'Can you turn a property around the same day a guest checks out?', 'a' => 'Yes, within our current weekend availability — this fits the Friday-in/Sunday-out pattern common to weekend-getaway short-lets in the Northern Suburbs. If your turnover schedule needs weekday cleaning, message us on WhatsApp and we\'ll see what we can arrange.'],
            ['q' => 'What if something is damaged or missing after a guest checks out?', 'a' => 'We do a quick check during every turnover and report anything damaged, missing, or left behind, so you can follow up with the guest or platform before the next booking arrives.'],
            ['q' => 'Do you supply fresh linen, or do we?', 'a' => 'We strip, launder-ready and remake with whatever linen and towels you supply on-site. If you\'d like us to help coordinate a linen rotation, ask us when booking.'],
            ['q' => 'What\'s the price based on?', 'a' => 'From R900 per turnover for a studio or 1-bedroom unit, plus R100 for each additional bedroom. Larger short-lets are quoted the same way as our other bedroom-based services.'],
        ],
    ],

    'spring-cleaning' => [
        'meta_title' => 'Spring Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Seasonal spring cleaning across Cape Town\'s Northern Suburbs — a full top-to-bottom reset including windows, curtains and cupboard interiors. Get a custom quote.',
        'label' => 'Spring Cleaning',
        'h1_line1' => 'Spring Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'The seasonal reset that goes further than a standard Deep Clean — every room, plus the windows, curtains and cupboard interiors that build up dust and grime over months, not weeks. Available year-round despite the name, but most requested at the change of season when homes need a genuine from-scratch refresh.',
        'included' => [
            'Every Deep Clean task as standard',
            'Windows & tracks cleaned inside',
            'Curtains & blinds dusted down',
            'Cupboard & wardrobe interiors wiped',
            'Patio or balcony swept & tidied',
            'Top-to-bottom seasonal reset',
        ],
        'ideal_for' => 'Homeowners wanting a genuine seasonal reset that goes beyond a standard Deep Clean, covering windows, curtains and storage spaces most cleans skip.',
        'blog_categories' => ['Deep Cleaning', 'Tips'],
        'hero_image' => '/images/works/home.avif',
        'pricing_mode' => 'custom',
        'pricing_notes' => [
            'Scoped to your home\'s size and the add-ons you choose',
            'Free walkthrough before we quote',
            'No obligation to book after your quote',
        ],
        'cta_label' => 'Get a Custom Quote',
        'faqs' => [
            ['q' => 'How is this different from a regular Deep Clean?', 'a' => 'Spring Cleaning covers everything a Deep Clean does, plus windows, curtains, blinds and cupboard interiors — the broader seasonal scope most regular cleans don\'t include.'],
            ['q' => 'Do I need to book this in spring specifically?', 'a' => 'No — the name reflects the seasonal-reset idea, but we book Spring Cleans year-round whenever a home needs that broader top-to-bottom refresh.'],
            ['q' => 'Why is this a custom quote instead of a fixed price?', 'a' => 'Scope varies a lot more than a standard Deep Clean — how many windows, how much curtain and blind work, whether you want the patio included. We quote after seeing the property so the price actually matches the job.'],
            ['q' => 'Can I choose which extras to include?', 'a' => 'Yes. Tell us what matters most — windows, curtains, cupboards, patio — and we\'ll scope the quote around it rather than a fixed one-size package.'],
        ],
    ],

    'oven-deep-cleaning' => [
        'meta_title' => 'Oven Deep Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Professional oven deep cleaning across Cape Town\'s Northern Suburbs — interior degreasing, racks and glass doors. Get a custom quote based on your oven type.',
        'label' => 'Oven Deep Cleaning',
        'h1_line1' => 'Oven Deep Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'Baked-on grease and carbon build-up that a wipe-down never touches — racks soaked and scrubbed separately, the interior degreased, and the glass door cleaned inside and out so you can actually see through it again.',
        'included' => [
            'Racks removed & soaked separately',
            'Interior degreased & scrubbed',
            'Glass door cleaned inside & out',
            'Door seals wiped down',
            'Control panel & handles cleaned',
            'Extractor/hood filter degreasing (on request)',
        ],
        'ideal_for' => 'Homes with a build-up of baked-on grease, and anyone whose oven hasn\'t had a proper interior clean in longer than they can remember.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/1.png',
        'pricing_mode' => 'custom',
        'pricing_notes' => [
            'Priced by oven type — built-in single, double, or freestanding',
            'Free walkthrough before we quote',
            'Extractor/hood filter degreasing quoted separately if needed',
        ],
        'cta_label' => 'Get a Custom Quote',
        'faqs' => [
            ['q' => 'What products do you use — are they safe for my kitchen?', 'a' => 'We use degreasing products suited to oven interiors and ventilate the space properly during and after the clean. Let us know about any specific sensitivities and we\'ll adjust accordingly.'],
            ['q' => 'Do you remove and clean the racks separately?', 'a' => 'Yes — racks are removed and soaked separately from the interior clean, since baked-on grease on racks usually needs longer soak time than the oven cavity itself.'],
            ['q' => 'How long does an oven deep clean take?', 'a' => 'Usually 1-2 hours depending on how built-up the grease is and whether it\'s a single, double, or freestanding oven — we\'ll confirm during the walkthrough.'],
            ['q' => 'Why is this a custom quote instead of a fixed price?', 'a' => 'Built-in single ovens, double ovens and freestanding stoves all take different time and products, so we quote after seeing the actual appliance rather than guessing a flat rate.'],
        ],
    ],

    'fridge-appliance-cleaning' => [
        'meta_title' => 'Fridge & Appliance Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Interior fridge, freezer and appliance cleaning across Cape Town\'s Northern Suburbs. Shelf & drawer removal, odour treatment. Get a custom quote.',
        'label' => 'Fridge & Appliance Cleaning',
        'h1_line1' => 'Fridge & Appliance',
        'h1_line2' => 'Cleaning',
        'intro' => 'A full interior reset for fridges, freezers and the other appliances that quietly build up spills and odours between deep cleans — shelves and drawers removed and washed properly, seals cleaned, and lingering odours treated at the source rather than masked.',
        'included' => [
            'Fridge & freezer interior cleaned',
            'Shelves & drawers removed & washed',
            'Door seals & gaskets cleaned',
            'Odour treatment at the source',
            'Microwave interior cleaned (on request)',
            'Dishwasher exterior & seal wipe-down (on request)',
        ],
        'ideal_for' => 'Households wanting a proper interior reset for fridges and freezers, and landlords refreshing appliances between tenants.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/2.png',
        'pricing_mode' => 'custom',
        'pricing_notes' => [
            'Priced by appliance count and fridge/freezer size',
            'Free walkthrough before we quote',
            'Other appliances (microwave, dishwasher) quoted alongside on request',
        ],
        'cta_label' => 'Get a Custom Quote',
        'faqs' => [
            ['q' => 'Do we need to empty the fridge before you arrive?', 'a' => 'Yes, please empty perishables beforehand — we handle the full clean of the empty interior, shelves and drawers once it\'s cleared.'],
            ['q' => 'Can you get rid of lingering odours?', 'a' => 'Yes, odour treatment is included as standard, targeting the source (usually seals, drains or built-up residue) rather than just masking the smell.'],
            ['q' => 'Do you clean other appliances too?', 'a' => 'Yes — microwave interiors and dishwasher exteriors/seals can be added on request when you book, quoted alongside the fridge and freezer clean.'],
            ['q' => 'Why is this a custom quote instead of a fixed price?', 'a' => 'Fridge and freezer sizes vary a lot, and how many appliances you want cleaned changes the job — we quote based on what you actually need done.'],
        ],
    ],

    'blind-curtain-cleaning' => [
        'meta_title' => 'Blind & Curtain Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Blind & curtain cleaning across Cape Town\'s Northern Suburbs — on-site dusting and deep cleaning for venetian, vertical blinds and fabric curtains. Get a custom quote.',
        'label' => 'Blind & Curtain Cleaning',
        'h1_line1' => 'Blind & Curtain',
        'h1_line2' => 'Cleaning',
        'intro' => 'Blinds and curtains collect dust and allergens that a regular clean rarely reaches — we clean venetian and vertical blinds on-site, and treat fabric curtains with a method suited to the material, so they come clean without damaging the fabric or mechanism.',
        'included' => [
            'On-site dusting & wipe-down for blinds',
            'Venetian & vertical blind cleaning',
            'Fabric curtain steam or spot treatment',
            'Dust & allergen removal',
            'Track & rail wiped down',
            'Care taken with delicate fabrics & mechanisms',
        ],
        'ideal_for' => 'Homes with built-up dust on blinds and curtains, allergy sufferers, and anyone refreshing window dressings before a seasonal clean.',
        'blog_categories' => ['Tips'],
        'hero_image' => '/images/works/home.avif',
        'pricing_mode' => 'custom',
        'pricing_notes' => [
            'Priced per blind or curtain, by type and size',
            'Free walkthrough before we quote',
            'Method adjusted for venetian, vertical, or fabric',
        ],
        'cta_label' => 'Get a Custom Quote',
        'faqs' => [
            ['q' => 'Do you clean blinds and curtains on-site, or take them away?', 'a' => 'On-site, in almost all cases — we bring the right method for venetian, vertical, or fabric to your home rather than removing items for off-site cleaning.'],
            ['q' => 'Is the process different for fabric curtains vs venetian blinds?', 'a' => 'Yes. Venetian and vertical blinds get a dusting and wipe-down process suited to the slats, while fabric curtains are treated with steam or spot-cleaning depending on the material.'],
            ['q' => 'Will cleaning damage delicate fabric or mechanisms?', 'a' => 'We assess the material and mechanism first and adjust our method accordingly — delicate fabrics and older mechanisms get a gentler approach.'],
            ['q' => 'Why is this a custom quote instead of a fixed price?', 'a' => 'Blind and curtain types vary widely in size, material and count per room, so we quote based on what\'s actually in your home rather than a flat per-item rate.'],
        ],
    ],

    'move-in-cleaning' => [
        'meta_title' => 'Move-In Cleaning Cape Town | Northern Suburbs | SpringKleaners',
        'meta_description' => 'Move-in cleaning for new homes across Cape Town\'s Northern Suburbs. A fresh-start sanitising clean before you unpack, from R1,200. Book online.',
        'label' => 'Move-In Cleaning',
        'h1_line1' => 'Move-In Cleaning',
        'h1_line2' => 'in Cape Town\'s Northern Suburbs',
        'intro' => 'A fresh-start clean for the home you\'re arriving into, not the one you\'re leaving behind — every cupboard, drawer and surface sanitised before you unpack a single box, so a new house feels like yours from day one instead of carrying traces of whoever lived there before.',
        'included' => [
            'Inside all cupboards & drawers wiped',
            'Kitchen & bathrooms fully sanitised',
            'All rooms vacuumed & mopped',
            'Light fixtures & switches wiped',
            'Windowsills & tracks cleaned',
            'Fresh-start clean, top to bottom',
        ],
        'ideal_for' => 'Buyers and tenants moving into a new home — whether newly built, newly rented, or previously occupied — who want it sanitised and cupboard-ready before unpacking.',
        'blog_categories' => ['End-of-Tenancy', 'Tips'],
        'hero_image' => '/images/works/home.avif',
        'faqs' => [
            ['q' => 'How is this different from your End-of-Tenancy clean?', 'a' => 'End-of-Tenancy is built for the person leaving — a letting-agent-standard clean tied to a deposit or handover checklist. Move-In Cleaning is for the person arriving — a fresh-start sanitising clean with no checklist or deposit process involved, focused on making a new space feel genuinely clean before you unpack.'],
            ['q' => 'Can you clean before we get the keys?', 'a' => 'We need access to the property to clean it, so this is usually scheduled for the day you get keys or shortly after — coordinate timing with your agent or the seller and we\'ll fit around it.'],
            ['q' => 'Do you clean empty properties or ones still being moved into?', 'a' => 'Empty or mostly-empty properties work best, since we can reach every cupboard, corner and surface without navigating boxes. If it\'s not fully empty, we\'ll work around what\'s there.'],
            ['q' => 'What\'s the price based on?', 'a' => 'From R1,200 for 2 bedrooms and 1 bathroom, plus R120 per extra bedroom and R100 per extra bathroom — the same pricing model as our End-of-Tenancy clean, since the scope of work is closely related.'],
        ],
    ],

];
